name: maven github action2
on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
    test2:
        name: Run test2 for maven2
        runs-on: ubuntu-latest
        steps:
            - name: get source code 
              uses: actions/checkout@v6
            # - name: setup java
            #   uses: actions/setup-java@v5
            #   with:
            #      distribution: 'temurin'
            #      java-version: '17'
            - name: Cache local Maven repository   # Dependency caching means saving downloaded dependencies from one workflow run and reusing them in later runs, instead of downloading everything again.
              uses: actions/cache@v6
              with:
                path: ~/.m2/repository
                key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
                restore-keys: |
                   ${{ runner.os }}-maven-
            - name: running tests
              run: mvn test
    build2:
        needs: test2
        name: building maven2
        runs-on: ubuntu-latest
        outputs:         # 4task jobOutput) job Output -> If you want to make a value available to another job, you create a job output.
            artifact-data: ${{ steps.artifact-name.outputs.artifact-data }} #4) takes value from step output
        steps: 
            - name: get source code 
              uses: actions/checkout@v6
            # - name: setup java
            #   uses: actions/setup-java@v5
            #   with:
            #      distribution: 'temurin'
            #      java-version: '17'
            - name: building jar artifacts file after cleaning ealier build 
              run: mvn clean package  
            - name: upload artifacts
              uses: actions/upload-artifact@v6
              with:
                name: artifact-data2    # 1task upload) artifact's name in GitHub
                path: |                 #1) to give multiple file as a path we can use pipe symbol and give the path of the files to be uploaded
                   target/*.jar          
                 # uploading all the jar files from target folder which is auto created by maven on the the runner machine to artifact-data2 
                 # Maven uses target as its standard build output directory.

            - name: Get the name of the output file
              id: artifact-name          #3)This gives the step an identifier.  You can later refer to this step using: steps.artifact-name
              run: find target/*.jar -type f -execdir echo 'artifact-data={}' >> $GITHUB_OUTPUT ';' #3task stepOutput) step output created-> output name = artifact-data ,output value = myapp-1.0.jar
    deploy2:
        needs: build2 
        name: taking artifacts of maven2
        runs-on: ubuntu-latest
        steps:  
          - name: Get artifacts data from build jobs   
            uses: actions/download-artifact@v7
            with: 
                name: artifact-data2   #2download ) name of the artifact to be downloaded from build2 job
          - name: List the downloaded artifacts
            run: ls  #2) list all the files and directories  in the current working directory of the runner machine
          - name: getting the artifact name from build2 job output
            run: echo ${{ needs.build2.outputs.artifact-data }} #5) for this the  jobs must contain needs: build




#---------------------run: find target/*.jar -type f -execdir echo 'artifact-data={}' >> $GITHUB_OUTPUT ';'  
# STEP OUTPUT
#  1) find target/*.jar -type f -execdir
   # find target/*.jar -> Find files matching target/*.jar. , -type f--> consider regular files ,  -execdir-> Execute a command in the directory where the found file exists.
#  2) echo 'artifact-data={}' 
   # The {} is replaced by the file that find discovered. ,  command means -> artifact-data=./myapp-1.0.jar
#  3) >> $GITHUB_OUTPUT -> This appends the output of the echo command to the $GITHUB_OUTPUT file, 

    # $GITHUB_OUTPUT is a special file provided by GitHub Actions to the running step. #You use it when you want to tell GitHub: Save this value as an output of this step."
    # GitHub Actions reads: artifact-data=myapp.jar from $GITHUB_OUTPUT and creates a step output

  
# echo 'artifact-data=some-file.jar' >> $GITHUB_OUTPUT  -> output name = artifact-data  , output value = myapp-1.0.jar
# so we have  StepID: artifact-name  & step Output:  artifact-data = myapp-1.0.jar ---can access it -->  ${{ steps.artifact-name.outputs.artifact-data }}


# JOB OUTPUT -> If you want to make that value available to another job, you create a job output.
#                 outputs:
#                    artifact-data: ${{ steps.artifact-name.outputs.artifact-data  }}   --> takes value from step output

# now we can access the job output in another job using: ${{ needs.build.outputs.artifact-data }} but other jobs must contain needs: build
 



#--------------------dependency caching 
# Every new runner starts fresh, so Maven may download dependencies again. 
# Dependency caching means saving downloaded dependencies from one workflow run and reusing them in later runs, instead of downloading everything again.
# https://github.com/actions/cache